### ISSUE TITLE
Behavior conditional on debugger is dangerous

### ISSUE THREAD

**Issue by haarg** [Ovid/moosex-extreme#11]
I think having behavior change depending on if the debugger is in use is a terrible idea. It is a recipe for heisenbugs and confusion.

Being immutable can have an impact on many things that are not obvious, like when other modules play around with `@ISA` or modify your symbol table. The warning issued could also produce a tremendous amount of spam in a larger code base.

Making `namespace::autoclean` conditional on the debugger is, I think, an even larger mistake. The extra subs will impact method resolution and leaving them in place could easily break classes.

Both of these are exactly the type of thing you might want to explore in the debugger.

`$^P` also can be used in cases other than using a full debugger. `Devel::Confess`, for example, enables only the flags to give more descriptive names to anonymous subs and evals. When using a module like `Devel::Confess` that uses a limited set of debug flags, there would not be any benefit at all to disabling `make_immutable` and `namespace::autoclean`.

**Comment by Ovid** [comment]
I could remove the `namespace::autoclean` bit, but if I don't disable `after_runtime`, the code dies and you can't even use the debugger.

If there was another (safer) way to apply `make_immutable`, that would possibly make this issue go away.

**Comment by Ovid** [comment]
`namespace::autoclean` is no longer removed when running under the debugger.

**Comment by Ovid** [comment]
Closing this as I can see no solution to the "make_immutable" issue under the debugger :( Feel free to reopen if you have any better ideas.

**Comment by haarg** [comment]
The issue with `after_runtime` isn't actually due to it being run too late, it's just a bug in B::Hooks::AtRuntime.

I've filed a PR to fix it: https://github.com/mauzo/B-Hooks-AtRuntime/pull/1

**Comment by Ovid** [comment]
Thank you! I'll reopen this ticket.

**Comment by Ovid** [comment]
I've upgraded to the latest `B::Hooks::AtRuntime` and tested it under the debugger. Works great. This change is now in `main`. Thanks for the help.
