### ISSUE TITLE
use of @_ within subs with signatures is a bad idea

### ISSUE THREAD

**Issue by haarg** [Ovid/moosex-extreme#20]
Using `@_` inside subs with signatures has been kept experimental in perl 5.36 because it is likely to be removed.

**Comment by Ovid** [comment]
Yeah, I need to fix that. Sloppy of me. Thanks!

**Comment by Ovid** [comment]
This was fixed in https://github.com/Ovid/moosex-extreme/pull/22 and is now in `main`. Thank you.
