### ISSUE TITLE
Consider supporting `init_arg => "_arg"` for `field`

### ISSUE THREAD

**Issue by tobyink** [Ovid/moosex-extreme#29]
The `field` implementation currently contains:

```perl
        if ( defined( my $init_arg = $options{init_arg} ) ) {
            throw_exception(
                'InvalidAttributeDefinition',
                attribute_name => $name,
                class_name     => $meta->name,
                messsage       => "The 'field.init_arg' must be absent or undef, not '$init_arg'",
            );
        }
        $options{init_arg} = undef;
```

Consider changing it to:

```perl
        $options{init_arg} //= undef;
```

Doesn't this defeat the purpose of `field`? Yes, and no.

It means that `field` is still a visual indicator that an attribute *should not* be provided to the constructor; and it means that the attribute still *defaults* to having no init_arg. But it now *allows* it to be provided, for purposes like unit testing.

I'd even be in favour of something like:

```perl
        if ( defined( my $init_arg = $options{init_arg} ) ) {
            $init_arg =~ /^_/ or throw_exception(
                'InvalidAttributeDefinition',
                attribute_name => $name,
                class_name     => $meta->name,
                messsage       => "The 'field.init_arg' must be absent, undef, or start with an underscore, not '$init_arg'",
            );
        }
        else {
            $options{init_arg} = undef;
        }
```

**Comment by Ovid** [comment]
You know, that sounds like a good idea. The testing issue has been bugging me. The underscore version is definitely preferable and more cleaning matches the intent. Would you like to make a PR?

**Comment by Ovid** [comment]
Note: if you're busy, I'll add this to my TODO list and make it happen. Just not sure when.

**Comment by tobyink** [comment]
I'll have a try this weekend.

**Comment by Ovid** [comment]
This was resolved in https://github.com/Ovid/moosex-extreme/pull/30
