### ISSUE TITLE
Steal feature from Moo: `builder => sub { ... }`

### ISSUE THREAD

**Issue by tobyink** [Ovid/moosex-extreme#31]
Moo supports:

```perl
has foo => (
  is => 'ro',
  lazy => 1,
  builder => sub { "default" },
);
```

As a shortcut for:

```perl
has foo => (
  is => 'ro',
  lazy => 1,
  builder => 1,
);

sub _build_foo { "default" }
```

How is this different from `default => sub {...}`? Because the builder is a method, so can be modified in child classes.

```perl
# in a child class
around _build_foo => sub {
  my ( $next, $self ) = @_;
  return uc( $self->$next );
};
```

**Comment by Ovid** [comment]
Along with `rwp`, this seems like a good idea to bring the two closer together.  Since [Mohammed Anwar is interested in porting this to Moo](https://twitter.com/cpan_author/status/1536988192632623105), I think that would be a great thing.

Wanna do another PR? :)

**Comment by tobyink** [comment]
Yes, sure, I can.
