### ISSUE TITLE
fields with no default/builder are still automatically "ro"

### ISSUE THREAD

**Issue by tobyink** [Ovid/moosex-extreme#37]
The following field is useless:

```perl
field foo => ( isa => Str );
```

It has no builder/default, no init_arg, and a read-only accessor. It can be set by directly accessing the object as a hashref, but we're trying to discourage that, right?

MooseX::Extended should either complain (warning? exception?) or should detect that the attribute would be unsettable and make the attribute "rw" or "rwp".

**Comment by Ovid** [comment]
That's a good point. Hmm.

I _think_ it should be a warning, but with some optional way of shutting off the warning. These "naked fields" could be set via the MOP and if someone was doing some heavy meta-programming, they might have a use case here. That use case seems unlikely, though. I might be overthinking it, but I'm trying to give people full control over this.

```perl
use MooseX::Extended excludes => ['naked_field_warning'];    # ugly name!
```

What do you think?

**Comment by tobyink** [comment]
`no warnings qw(MooseX::Extended::naked_fields);` could work too, using warnings::register, etc.

**Comment by Ovid** [comment]
I think that sounds great. Wanna do another PR?

**Comment by Ovid** [comment]
Also, if you're tired of PRs, that's fine and I'm happy to do it.

**Comment by tobyink** [comment]
I'll look into it in the next few days.

**Comment by Ovid** [comment]
This is addressed via https://github.com/Ovid/moosex-extreme/pull/38
