### ISSUE TITLE
Typo in documentation for is=>rwp

### ISSUE THREAD

**Issue by tobyink** [Ovid/moosex-extreme#39]
https://github.com/Ovid/moosex-extreme/commit/c7a8e35492944bbfa6d2ae7e28913d28a2a931bf#r77576285

Also there should probably be a test case to check that public method for the attribute is a reader only.

**Comment by Ovid** [comment]
I've added the test case.

**Comment by Ovid** [comment]
And updated the docs. Should have closed this yesterday.
